PRAGMA foreign_keys=1;
.headers on
.mode columns

.open movieDB.db

DROP TABLE MOVIE;
DROP TABLE ACTOR;
DROP TABLE DIRECTOR;
DROP TABLE SCREENWRITER;
DROP TABLE LOCATION;
DROP TABLE SONG;
DROP TABLE MOVIE_LOCATION;
DROP TABLE MOVIE_SONG;
DROP TABLE WRITTEN_BY;
DROP TABLE ACTED_IN;

CREATE TABLE MOVIE (
	m_title VARCHAR(30) NOT NULL,
	m_release_date DATE NOT NULL,
	genre VARCHAR(15),
	minutes INT,
	language VARCHAR(20),
	m_producer VARCHAR(30),
	origin VARCHAR(20),
	PRIMARY KEY (m_title, m_release_date)
);

CREATE TABLE ACTOR(
	a_ID INT NOT NULL CHECK(a_ID > 0 AND a_ID <= 99999),
	fname VARCHAR(20) NOT NULL,
	lname VARCAHR(20) NOT NULL,
	a_DOB DATE,
	gender CHAR CHECK(gener = 'M' OR gender = 'F'),
	a_nationality VARCHAR(20),
	a_active_form VARCHAR(20),
	PRIMARY KEY(a_ID)
);

CREATE TABLE DIRECTOR(
	d_ID INT NOT NULL CHECK(a_ID > 0 AND a_ID <= 99999),
	fname VARCHAR(20) NOT NULL,
	lname VARCAHR(20) NOT NULL,
	d_DOB DATE,
	gender CHAR CHECK(gener = 'M' OR gender = 'F'),
	d_nationality VARCHAR(20),
	d_active_form VARCHAR(20),
	movie VARCHAR(30) NOT NULL,
	movie_release DATE NOT NULL
	PRIMARY KEY(d_ID),
	FOREIGN KEY(movie) REFERENCES MOVIE(m_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(movie_release) REFERENCES MOVIE(m_release_date) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE SCREENWRITER(
	w_ID INT NOT NULL CHECK(a_ID > 0 AND a_ID <= 99999),
	fname VARCHAR(20) NOT NULL,
	lname VARCAHR(20) NOT NULL,
	w_DOB DATE,
	gender CHAR CHECK(gener = 'M' OR gender = 'F'),
	w_nationality VARCHAR(20),
	w_active_form VARCHAR(20),
	PRIMARY KEY(w_ID)
);

CREATE TABLE LOCATION(
	country VARCHAR(30) NOT NULL,
	region VARCHAR(30) NOT NULL,
	place VARCHAR(30) NOT NULL,
	PRIMARY KEY(county, region, place)
);

CREATE TABLE SONG(
	s_title VARCHAR(30) NOT NULL,
	s_artist VARCHAR(20) NOT NULL,
	s_release_date DATE NOT NULL,
	s_producer VARCHAR(30),
	album VARCHAR(20),
	PRIMARY KEY(s_title, s_artist, s_release_date)
);

CREATE TABLE MOVIE_LOCATION(
	movie VARCHAR(30) NOT NULL,
	movie_release DATE NOT NULL,
	country VARCHAR(30) NOT NULL,
	region VARCHAR(30) NOT NULL,
	place VARCHAR(30) NOT NULL,
	PRIMARY KEY(movie, movie_release, country, region, place),
	FOREIGN KEY(movie) REFERENCES MOVIE(m_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(movie_release) REFERENCES MOVIE(m_release_date) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(country) REFERENCES LOCATION(country) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(region) REFERENCES LOCATION(region) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(place) REFERENCES LOCATION(place) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE MOVIE_SONG(
	movie VARCHAR(30) NOT NULL,
	movie_release DATE NOT NULL,
	song VARCHAR(30) NOT NULL,
	song_release DATE NOT NULL,
	artist VARCHAR(20) NOT NULL,
	PRIMARY KEY(movie, movie_release, country, region, place),
	FOREIGN KEY(movie) REFERENCES MOVIE(m_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(movie_release) REFERENCES MOVIE(m_release_date) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(song) REFERENCES SONG(s_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(song_release) REFERENCES SONG(s_release_date) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(artist) REFERENCES SONG(s_artist) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE WRITTEN_BY(
	movie VARCHAR(30) NOT NULL,
	movie_release DATE NOT NULL,
	writer INT NOT NULL CHECK(a_ID > 0 AND a_ID <= 99999),
	PRIMARY KEY(movie, movie_release, writer),
	FOREIGN KEY(movie) REFERENCES MOVIE(m_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(movie_release) REFERENCES MOVIE(m_release_date) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(writer) REFERENCES SCREENWRITER(w_ID) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE ACTED_IN(
	movie VARCHAR(30) NOT NULL,
	movie_release DATE NOT NULL,
	actor INT NOT NULL CHECK(a_ID > 0 AND a_ID <= 99999),
	PRIMARY KEY(movie, movie_release, writer),
	FOREIGN KEY(movie) REFERENCES MOVIE(m_title) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(movie_release) REFERENCES MOVIE(m_release_date) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY(actor) REFERENCES ACTOR(a_ID) ON UPDATE CASCADE ON DELETE CASCADE
);




